"""
# Multi-Modal Representation Learning (Bi-Encoder)

1. Utilizes all intra-hour factors generated by FactorPool.
2. Employs a Transformer Encoder on the past 7 days of hourly (Return & Volume).
3. Employs a Transformer Encoder on the past 2 hours of minute-level (Return & Volume).
4. Feeds concatenated 1D vectors into a unified presentation.
5. Learns similarity targets mapped against a Future 24-hour return Transformer.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import math
import sys
from sklearn.preprocessing import StandardScaler

# Import FactorPool and all specific factors
sys.path.append('d:/py_projects/crypto')
from factor_pool import (FactorPool, WeeklyVolumeZScore, MonthlyVolumeZScore, 
                         RollingMaxVolumePercentage, PriceVolumeCorrelation, 
                         PriceVolumeConfirmedReturn, MinZScore, RSI, 
                         BTCETH24hCorrelation, BTCETHIntraHourCorrelation, 
                         IntraHourVolatility, IntraHourVWAP, IntraHourHighLowRange, 
                         IntraHourVolumeSpike, IntraHourPriceVolumeTrend, HourlyReturn, 
                         MACD, BollingerBandsWidth, Alpha1, Alpha101, ADX, FisherTransform, 
                         PercentageATR, MoneyFlowIndex, HilbertTransformPhase)

# Set seed for reproducibility
torch.manual_seed(42)
np.random.seed(42)

print("Loading data and computing factors...")
pool = FactorPool()
pool.load_data('data/btcusd_1-min_data.csv', 'data/ethusd_1min_ohlc.csv')

# Populate factors
pool.add_factor(WeeklyVolumeZScore())
pool.add_factor(MonthlyVolumeZScore())
pool.add_factor(RollingMaxVolumePercentage())
pool.add_factor(PriceVolumeCorrelation(pool.btc_data))
pool.add_factor(PriceVolumeConfirmedReturn(pool.btc_data))
pool.add_factor(MinZScore())
pool.add_factor(RSI())
pool.add_factor(BTCETH24hCorrelation())
pool.add_factor(BTCETHIntraHourCorrelation(pool.btc_data, pool.eth_data))
pool.add_factor(IntraHourVolatility(pool.btc_data))
pool.add_factor(IntraHourVWAP(pool.btc_data))
pool.add_factor(IntraHourHighLowRange(pool.btc_data))
pool.add_factor(IntraHourVolumeSpike(pool.btc_data))
pool.add_factor(IntraHourPriceVolumeTrend(pool.btc_data))
pool.add_factor(HourlyReturn())
pool.add_factor(MACD())
pool.add_factor(BollingerBandsWidth())
pool.add_factor(Alpha1())
pool.add_factor(Alpha101())
pool.add_factor(ADX())
pool.add_factor(FisherTransform())
pool.add_factor(PercentageATR())
pool.add_factor(MoneyFlowIndex())
pool.add_factor(HilbertTransformPhase())

factor_df = pool.compute_all()
factor_df.replace([np.inf, -np.inf], np.nan, inplace=True)
factor_df.dropna(inplace=True)

feature_cols = [c for c in factor_df.columns if c not in ['hour_close', 'hour_volume']]
full_factor = factor_df[feature_cols].resample('1h').ffill()

# Extract raw Hourly series
hourly_data = pool.get_hourly_data()
hourly_ret = hourly_data['Close'].pct_change().fillna(0)
hourly_vol = np.log1p(hourly_data['Volume'])
hourly_features = pd.concat([hourly_ret, hourly_vol], axis=1)
hourly_features.columns = ['Return', 'Volume']
full_hourly = hourly_features.resample('1h').ffill()

# Extract raw Minute series
btc_min = pool.btc_data.set_index('datetime_et')
min_ret = btc_min['close'].pct_change().fillna(0)
min_vol = np.log1p(btc_min['volume'])
min_features = pd.concat([min_ret, min_vol], axis=1)
min_features.columns = ['Return', 'Volume']
full_min = min_features.resample('1min').ffill()

# Sync index intersections (to guarantee sequences won't raise exceptions)
valid_start = max(full_hourly.index[167], full_min.index[119])
valid_end = full_hourly.index[-25]
valid_times = full_factor.index[(full_factor.index >= valid_start) & (full_factor.index <= valid_end)]

hourly_idx = {t: i for i, t in enumerate(full_hourly.index)}
min_idx = {t: i for i, t in enumerate(full_min.index)}
factor_idx = {t: i for i, t in enumerate(full_factor.index)}

time_grid = [t for t in valid_times if t in hourly_idx and t in min_idx]

# Normalizing parameters
scaler_h = StandardScaler()
hourly_arr = scaler_h.fit_transform(full_hourly.values)

scaler_m = StandardScaler()
min_arr = scaler_m.fit_transform(full_min.values)

scaler_f = StandardScaler()
factor_arr = scaler_f.fit_transform(full_factor.values)

# Generate Targets (Next 24hr Vol-Weighted Return Vectors & Next 1 Day Cumulative Return)
t_to_tgt = {}
t_to_ret = {}
for t in time_grid:
    h_i = hourly_idx[t]
    # Next 24 hours raw returns & log-volumes
    f_rets = full_hourly['Return'].values[h_i+1:h_i+25]
    f_vols = full_hourly['Volume'].values[h_i+1:h_i+25]
    vol_weighted_ret = f_rets * f_vols
    
    # Next 1 day cumulative simple return
    cum_ret = np.prod(1 + f_rets) - 1
    
    t_to_tgt[t] = vol_weighted_ret
    t_to_ret[t] = cum_ret

# Train / Test Date Splitting
split_date_train = pd.to_datetime('2021-01-01', utc=True).tz_convert('America/New_York')
split_date_test = pd.to_datetime('2025-01-01', utc=True).tz_convert('America/New_York')

train_times_all = [t for t in time_grid if split_date_train <= t < split_date_test]
test_times = [t for t in time_grid if t >= split_date_test]

# Equally sample 50k records for training
if len(train_times_all) > 50000:
    train_times = np.random.choice(train_times_all, size=50000, replace=False).tolist()
else:
    train_times = train_times_all

print(f"Prepared Data: {len(train_times)} Train samples, {len(test_times)} Test samples.")

class CryptoTripletDataset(Dataset):
    def __init__(self, times, hourly_arr, min_arr, factor_arr, hourly_idx, min_idx, factor_idx, t_to_tgt):
        self.times = times
        self.hourly_arr = hourly_arr
        self.min_arr = min_arr
        self.factor_arr = factor_arr
        self.hourly_idx = hourly_idx
        self.min_idx = min_idx
        self.factor_idx = factor_idx
        
        self.targets = np.array([t_to_tgt[t] for t in times])
        norms = np.linalg.norm(self.targets, axis=1, keepdims=True)
        self.norm_targets = self.targets / (norms + 1e-8)
        
    def __len__(self):
        return len(self.times)
        
    def _get_tensors(self, i):
        t = self.times[i]
        h_i = self.hourly_idx[t]
        m_i = self.min_idx[t]
        f_i = self.factor_idx[t]
        
        h_seq = self.hourly_arr[h_i - 167 : h_i + 1]
        m_seq = self.min_arr[m_i - 119 : m_i + 1]
        f_vec = self.factor_arr[f_i]
        
        return (torch.FloatTensor(h_seq), 
                torch.FloatTensor(m_seq), 
                torch.FloatTensor(f_vec))
                
    def __getitem__(self, i):
        anchor = self._get_tensors(i)
        
        # Dynamic Positive/Negative mining based on Cosine Similarity
        # Sub-sample 50 candidates dynamically to keep memory/CPU low
        cand_indices = np.random.choice(len(self.times), min(50, len(self.times)), replace=False)
        sims = np.dot(self.norm_targets[cand_indices], self.norm_targets[i])
        
        pos_idx = cand_indices[np.argmax(sims)]
        neg_idx = cand_indices[np.argmin(sims)]
        
        positive = self._get_tensors(pos_idx)
        negative = self._get_tensors(neg_idx)
        
        return anchor, positive, negative

class CryptoEvalDataset(Dataset):
    def __init__(self, times, hourly_arr, min_arr, factor_arr, hourly_idx, min_idx, factor_idx, t_to_ret):
        self.times = times
        self.hourly_arr = hourly_arr
        self.min_arr = min_arr
        self.factor_arr = factor_arr
        self.hourly_idx = hourly_idx
        self.min_idx = min_idx
        self.factor_idx = factor_idx
        self.rets = [t_to_ret[t] for t in times]
        
    def __len__(self):
        return len(self.times)
        
    def __getitem__(self, i):
        t = self.times[i]
        h_i = self.hourly_idx[t]
        m_i = self.min_idx[t]
        f_i = self.factor_idx[t]
        
        h_seq = self.hourly_arr[h_i - 167 : h_i + 1]
        m_seq = self.min_arr[m_i - 119 : m_i + 1]
        f_vec = self.factor_arr[f_i]
        
        return (torch.FloatTensor(h_seq), 
                torch.FloatTensor(m_seq), 
                torch.FloatTensor(f_vec),
                torch.FloatTensor([self.rets[i]]))

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super(PositionalEncoding, self).__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe.unsqueeze(0))

    def forward(self, x):
        x = x + self.pe[:, :x.size(1)]
        return x

class SeriesTransformerEncoder(nn.Module):
    def __init__(self, input_dim=2, d_model=64, nhead=8, num_layers=4, output_dim=32, seq_len=168):
        super().__init__()
        self.input_linear = nn.Linear(input_dim, d_model)
        self.pos_encoder = PositionalEncoding(d_model, max_len=seq_len)
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead, dim_feedforward=d_model*4, batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.output_linear = nn.Linear(d_model, output_dim)
        
    def forward(self, x):
        x = self.input_linear(x)
        x = self.pos_encoder(x)
        x = self.transformer_encoder(x)
        x = x.mean(dim=1)
        x = self.output_linear(x)
        return x

class BiEncoderModel(nn.Module):
    def __init__(self, num_factors, d_model=64, nhead=8, num_layers=4, embed_dim=32, final_dim=64):
        super().__init__()
        self.hourly_encoder = SeriesTransformerEncoder(input_dim=2, d_model=d_model, nhead=nhead, num_layers=num_layers, output_dim=embed_dim, seq_len=168)
        self.minute_encoder = SeriesTransformerEncoder(input_dim=2, d_model=d_model, nhead=nhead, num_layers=num_layers, output_dim=embed_dim, seq_len=120)
        
        self.fc_factors = nn.Sequential(
            nn.Linear(num_factors, 64),
            nn.ReLU(),
            nn.Linear(64, embed_dim)
        )
        
        # Modality Fusion Encoder
        fusion_layer = nn.TransformerEncoderLayer(d_model=embed_dim, nhead=4, dim_feedforward=embed_dim*4, batch_first=True)
        self.fusion_encoder = nn.TransformerEncoder(fusion_layer, num_layers=2)
        
        # Final projection
        self.fc_final = nn.Sequential(
            nn.Linear(embed_dim, 128),
            nn.ReLU(),
            nn.Linear(128, final_dim)
        )
        
    def forward(self, h_seq, m_seq, f_vec):
        h_emb = self.hourly_encoder(h_seq)
        m_emb = self.minute_encoder(m_seq)
        f_emb = self.fc_factors(f_vec)
        
        # Stack into sequence for the fusion encoder: (batch, 3, embed_dim)
        stacked_emb = torch.stack([h_emb, m_emb, f_emb], dim=1)
        
        fused_seq = self.fusion_encoder(stacked_emb)
        fused_emb = fused_seq.mean(dim=1)
        
        final_emb = self.fc_final(fused_emb)
        return final_emb

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model = BiEncoderModel(num_factors=len(feature_cols)).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.TripletMarginLoss(margin=1.0)

train_dataset = CryptoTripletDataset(train_times, hourly_arr, min_arr, factor_arr, hourly_idx, min_idx, factor_idx, t_to_tgt)
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True)

epochs = 5
print("Starting Triplet-Loss Bi-Encoder training...")

for epoch in range(epochs):
    model.train()
    epoch_loss = 0
    for anchor, positive, negative in train_dataloader:
        a_h, a_m, a_f = [t.to(device) for t in anchor]
        p_h, p_m, p_f = [t.to(device) for t in positive]
        n_h, n_m, n_f = [t.to(device) for t in negative]
        
        optimizer.zero_grad()
        
        anchor_emb = model(a_h, a_m, a_f)
        pos_emb = model(p_h, p_m, p_f)
        neg_emb = model(n_h, n_m, n_f)
        
        loss = criterion(anchor_emb, pos_emb, neg_emb)
        
        loss.backward()
        optimizer.step()
        
        epoch_loss += loss.item()
    
    print(f"Epoch {epoch+1}/{epochs}, Triplet Loss: {epoch_loss/len(train_dataloader):.4f}")

print("Training complete.")

print("Evaluating Test Set via Historical Pattern Retrieval...")
model.eval()

# 1. Embed the Historical Training Set for the Retrieval DB
train_eval_dataset = CryptoEvalDataset(train_times, hourly_arr, min_arr, factor_arr, hourly_idx, min_idx, factor_idx, t_to_ret)
train_eval_loader = DataLoader(train_eval_dataset, batch_size=256, shuffle=False)

train_embs = []
train_actuals = []
with torch.no_grad():
    for h, m, f, target in train_eval_loader:
        emb = model(h.to(device), m.to(device), f.to(device))
        train_embs.append(emb.cpu())
        train_actuals.append(target)
        
train_embs = torch.cat(train_embs, dim=0).numpy()
train_actuals = torch.cat(train_actuals, dim=0).numpy().flatten()

# 2. Process the 2025 Test Set
test_eval_dataset = CryptoEvalDataset(test_times, hourly_arr, min_arr, factor_arr, hourly_idx, min_idx, factor_idx, t_to_ret)
test_eval_loader = DataLoader(test_eval_dataset, batch_size=256, shuffle=False)

test_preds = []
test_real_rets = []

from sklearn.metrics.pairwise import cosine_similarity

with torch.no_grad():
    for h, m, f, target in test_eval_loader:
        emb = model(h.to(device), m.to(device), f.to(device)).cpu().numpy()
        
        # Calculate Similarity of Test Embeddings against all Train Embeddings
        sims = cosine_similarity(emb, train_embs)
        
        # Retrieve Top 5 Similar Patterns' indexes
        top_k_idx = np.argsort(sims, axis=1)[:, -5:]
        
        # Average Next 1-Day Return of those patterns
        pred = np.mean(train_actuals[top_k_idx], axis=1)
        
        test_preds.extend(pred)
        test_real_rets.extend(target.numpy().flatten())
        
test_preds = np.array(test_preds)
test_real_rets = np.array(test_real_rets)

# Calculate MSE difference
mse = np.mean((test_preds - test_real_rets)**2)
print(f"Test Set Prediction MSE (Analog Forecasting): {mse:.6f}")